// Code generated by github.com/mackee/go-sqlla/v2/cmd/sqlla. DO NOT EDIT.
package postgresql

import "time"

func (i Identity) DefaultInsertHook(_q identityInsertSQL) (identityInsertSQL, error) {
	now := time.Now()
	return _q.
		ValueCreatedAt(now).
		ValueUpdatedAt(now), nil
}

func (i Identity) DefaultUpdateHook(_q identityUpdateSQL) (identityUpdateSQL, error) {
	now := time.Now()
	return _q.
		SetUpdatedAt(now), nil
}
