-- generated by github.com/mackee/go-genddl. DO NOT EDIT!!!

DROP TABLE IF EXISTS "accounts";

CREATE TABLE "accounts" (
    "id" BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR NOT NULL,
    "embedding" vector(3) NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL
) ;


DROP TABLE IF EXISTS "groups";

CREATE TABLE "groups" (
    "id" BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR NOT NULL,
    "leader_account_id" BIGINT NOT NULL,
    "sub_leader_account_id" BIGINT NULL,
    "child_group_id" BIGINT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL
) ;


DROP TABLE IF EXISTS "identities";

CREATE TABLE "identities" (
    "id" BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "account_id" BIGINT NOT NULL,
    "email" VARCHAR NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL
) ;

