-- generated by github.com/mackee/go-genddl. DO NOT EDIT!!!

DROP TABLE IF EXISTS `group`;

CREATE TABLE `group` (
    `id` BIGINT unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `leader_user_id` BIGINT unsigned NOT NULL,
    `sub_leader_user_id` BIGINT unsigned NULL,
    `child_group_id` BIGINT unsigned NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
    `id` BIGINT unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `age` BIGINT NULL,
    `rate` DOUBLE NOT NULL DEFAULT 0,
    `icon_image` BLOB NOT NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NULL,
    UNIQUE (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `user_external`;

CREATE TABLE `user_external` (
    `id` BIGINT unsigned NOT NULL PRIMARY KEY,
    `user_id` BIGINT unsigned NOT NULL,
    `icon_image` BLOB NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `user_item`;

CREATE TABLE `user_item` (
    `id` BIGINT unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `user_id` BIGINT unsigned NOT NULL,
    `item_id` VARCHAR(191) NOT NULL,
    `is_used` BOOLEAN NOT NULL,
    `has_extension` BOOLEAN NULL,
    `used_at` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `user_sns`;

CREATE TABLE `user_sns` (
    `id` BIGINT unsigned NOT NULL PRIMARY KEY,
    `sns_type` VARCHAR(191) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

