-- generated by github.com/mackee/go-genddl. DO NOT EDIT!!!

DROP TABLE IF EXISTS `item`;

CREATE TABLE `item` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
    `id` BIGINT unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `age` BIGINT NULL,
    `rate` DOUBLE NOT NULL DEFAULT 0,
    `icon_image` BLOB NOT NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NULL,
    UNIQUE (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `user_external`;

CREATE TABLE `user_external` (
    `id` BIGINT unsigned NOT NULL PRIMARY KEY,
    `user_id` BIGINT unsigned NOT NULL,
    `icon_image` BLOB NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `user_item`;

CREATE TABLE `user_item` (
    `id` BIGINT unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `user_id` BIGINT unsigned NOT NULL,
    `item_id` VARCHAR(191) NOT NULL,
    `is_used` BOOLEAN NOT NULL,
    `has_extension` BOOLEAN NULL,
    `used_at` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `user_sns`;

CREATE TABLE `user_sns` (
    `id` BIGINT unsigned NOT NULL PRIMARY KEY,
    `sns_type` VARCHAR(191) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE VIEW `user_item_detail`
  (`ui_id`, `ui_user_id`, `ui_item_id`, `ui_is_used`, `ui_has_extension`, `ui_used_at`, `i_id`, `i_name`, `u_id`, `u_name`, `u_age`, `u_rate`, `u_icon_image`, `u_created_at`, `u_updated_at`) AS
  SELECT
    ui.id, ui.user_id, ui.item_id, ui.is_used, ui.has_extension, ui.used_at,
    i.id, i.name,
    u.id, u.name, u.age, u.rate, u.icon_image, u.created_at, u.updated_at
  FROM user_item AS ui
    INNER JOIN item AS i ON ui.item_id = i.id
    INNER JOIN user AS u ON ui.user_id = u.id;

