-- generated by github.com/mackee/go-genddl. DO NOT EDIT!!!

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
    `id` BIGINT unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `age` BIGINT NULL,
    `rate` DOUBLE NOT NULL DEFAULT 0,
    `icon_image` BLOB NOT NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NULL,
    UNIQUE (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS `user_item`;

CREATE TABLE `user_item` (
    `id` BIGINT unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `user_id` BIGINT unsigned NOT NULL,
    `item_id` VARCHAR(191) NOT NULL,
    `is_used` BOOLEAN NOT NULL,
    `has_extension` BOOLEAN NULL,
    `used_at` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

