// Code generated by github.com/mackee/go-sqlla/v2/cmd/sqlla. DO NOT EDIT.
package example

import (
	"context"
	"time"

	"github.com/mackee/go-sqlla/v2"
)

func (q userSelectSQL) CountContext(ctx context.Context, db sqlla.DB, column string) (int64, error) {
	query, args, err := q.SetColumns("COUNT(" + column + ")").ToSql()
	if err != nil {
		return 0, err
	}
	row := db.QueryRowContext(ctx, query, args...)
	var count int64
	if err := row.Scan(&count); err != nil {
		return 0, err
	}
	return count, nil
}

func (u User) DefaultInsertHook(q userInsertSQL) (userInsertSQL, error) {
	now := time.Now()
	return q.
		ValueCreatedAt(now), nil
}

func (u User) DefaultInsertOnDuplicateKeyUpdateHook(q userInsertOnDuplicateKeyUpdateSQL) (userInsertOnDuplicateKeyUpdateSQL, error) {
	return q.
		SameOnUpdateUpdatedAt(), nil
}

type Users []*User

func (u Users) Ids() []UserId {
	vs := make([]UserId, len(u))
	for i := range u {
		vs[i] = u[i].Id
	}
	return vs
}

func (u Users) Names() []string {
	vs := make([]string, len(u))
	for i := range u {
		vs[i] = u[i].Name
	}
	return vs
}

func (u Users) AssociateByIds() map[UserId]*User {
	m := make(map[UserId]*User, len(u))
	for _, v := range u {
		m[v.Id] = v
	}
	return m
}

func (u Users) GroupByNames() map[string]Users {
	m := make(map[string]Users, len(u))
	for _, v := range u {
		m[v.Name] = append(m[v.Name], v)
	}
	return m
}
