// Code generated by github.com/mackee/go-sqlla/v2/cmd/sqlla - DO NOT EDIT.
package example

import (
	"context"
	"github.com/mackee/go-sqlla/v2"
)

func (q userSelectSQL) CountContext(ctx context.Context, db sqlla.DB, column string) (int64, error) {
	query, args, err := q.SetColumns("COUNT(" + column + ")").ToSql()
	if err != nil {
		return 0, err
	}
	row := db.QueryRowContext(ctx, query, args...)
	var count int64
	if err := row.Scan(&count); err != nil {
		return 0, err
	}
	return count, nil
}
